# Site settings
description: Guia de Acessibilidade de Interfaces Web com foco em aspectos do Autismo
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://talitapagani.com/gaia" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Talita Pagani
user_description: Mestranda em Computação na UFSCar
user_title: Pesquisadora
email: contato@talitapagani.com
twitter_username: talitapagani
github_username:  talitapagani
gplus_username:  talitapagani
disqus_username: talitapagani

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Categorias
    url: /categorias
  - title: Tags
    url: /tags
  - title: Sobre o projeto
    url: /sobre

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
